language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm i
- npm i --only=dev
script:
- npm --version
deploy:
  provider: npm
  email: info.dvgamer@gmail.com
  api_key:
    secure: abZOsfnm8BEhLlQaUUvf2/9494Yk1A9kM0nip4XUzQWF+awDMWZNkeAUAvwEjCt9H3h4nh8ngbVqUt8IbdhrDpjyVT8ac48Iz7Gxuute+Wxv4CM+s79eJariy0uMS5UBoEHgt4jqwmPDzeaOL7ddE/15s2huA5W0NklPXbX5Trpi6iLID7WbhUNykAUBl6uI6vBT3Z66PU4LklK48qAlMtsN54qP5MjJY54Qt8C3Ws6cTv96LIrrbtENSvVbLjrgTjYq0mhzfTPMyJXa2sXjTJE6iqOji8SdylUE1gAxxh8XY0bJtnz8eUQCSMjscgUoG49/l3H9oA1BU+fAgV2AqZOjp+I5xzTa6nZi8e6C78hEl34Q3TlIMKGtiBiskEzk7dNFSbsPjFbTl0MrH+fw6ryRv2XAB4l02UVSIuSSmOAettsGCCV2xFURpac+48wGn2QMW1+u+EGVM7VHaIPTXJaA+cxXhOt0kDLM4Ww+KebAl6jZ81AlTdMchl20dCh1rf6jdh9ZWtJwtWDDIJfKJcWpuc5aZj8bbwZHHMm9gj8fsP236P9YNWLe1U+rCTf93RO6WFgglNF9ltqgnu78PjcdDUe7FvdxnZ1/qyqo+JVUfwcRh58oItpsOC5CTSNF7foMYXyxEf9auaEfm5fQh+1iuvVnFsGaHz2Gh12GO38=
  on:
    branch: master
    tags: true
notifications:
  slack:
    rooms:
    - touno-io:ZcDavq693hAAVtvH4ugh9Oen
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: never
    on_error: always
