language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm i
- npm i --only=dev
script:
- npm --version
deploy:
  provider: npm
  email: info.dvgamer@gmail.com
  api_key:
    secure: J9yql5Tiy+cKWEBcaCu4VJ5us0sTq+y8TRixnKQum6GFZkOHrdQyUS9ODrHFByQrRlndncygtGMRwGRi8TEg4pgIK0o7gmN6vk9q/Z818Ku/ufE8ojaeF1f0JOOUXa6LidPDSffQqb0aJ762lBof7UX67ee83IW/AIyR/zwV9aBHHsLvHWWnF282T0A4SatDP4PXtzpA2XHjtMEP7zyqIU47cuYAGv6YcigviKAjIhme5lqtVopfViZYiRsRh5VXwJHO97ID8yDeD5Zj3VQo3l18VNCGNcSYAmhrCf2ejXuW6UkzuSdgcPxctArOgy7NF1zQ1X0zvZ3BxJ3Q26dUB0sfppgY0tgPCGKHazl0VOuEzEkQYBpa4Hry6o+aLTU2pn/nqPUkv9mqDnTgH9LhOtno2eZKbF3Othn82eWFyrxlGpxqAFJgG7uyaHsulbyLZSibQuM+j6iI1HsXJqrMvBdEbxN8jhn4PuhXvcOgiGYTv6/Vnn4sFFGfsV6QmGv2rFvW8es3IUr8JFvGi1ZOW2KEkV42D6JBU3PEYOJlYpg+nrGrdEZW9uy5VoT3+zKS6WNJUI15C2T9lCSSLYApPnwdcwhiCUQr1MqA0RMYLd9JKUdQmf01fzCz1KMB5IpV+XnD4MiY91Laa4Z+9ekAeoVm9qtfH8LdnhW+CfkIujs=
  on:
    branch: master
    tags: true
notifications:
  slack:
    rooms:
    - touno-io:ZcDavq693hAAVtvH4ugh9Oen
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: never
    on_error: always
